include: package:flutter_lints/flutter.yaml

# Additional information about this file can be found at
# https://dart.dev/tools/analysis
# https://pub.dev/packages/flutter_lints
# https://dart.dev/guides/language/analysis-options

linter:
  rules:
    # Printing is useful for developers in this example app
    avoid_print: false
