[tasks.lint]
description = "Lint"
dir = "push"
run = [
  'dart format --set-exit-if-changed .',
  'swiftformat --lint --exclude example/macos/Flutter/GeneratedPluginRegistrant.swift .',
]

[tasks.format]
description = "Format"
dir = "push"
run = [
  # https://dart.dev/tools/dart-format
  'dart format .', # https://github.com/nicklockwood/SwiftFormat, not https://github.com/apple/swift-format
  'swiftformat --exclude example/macos/Flutter/GeneratedPluginRegistrant.swift .', # TODO Use ktlint?
]

[tasks.codegen]
description = "Generate code"
dir = "push"
run = [
  'dart run pigeon --input pigeons/push_api.dart',
]
# TO support macOS, we run codegen for all platforms (except iOS and macOS) twice so that we can run on iOS and macOS, but it's idempotent so it's okay. 
# Ideally, Pigeon supports multiple paths for the same language (a swiftOut [array])
# 'dart run pigeon --input pigeons/push_api.dart --swift_out ./push/macos/Classes/serialization/PushApi.swift',

[tasks.publish]
description = "Publish to pub.dev"
dir = "push"
run = [
  'flutter pub publish',
]
