[tasks.lint]
description = "Lint"
run = [
  'dart format --set-exit-if-changed .',
  'swiftformat --lint --exclude example/macos/Flutter/GeneratedPluginRegistrant.swift .',
  'flutter analyze',
]

[tasks.format]
description = "Format"
run = [
  'dart fix --apply',
  'dart format .', # https://dart.dev/tools/dart-format
  'swiftformat --exclude example/macos/Flutter/GeneratedPluginRegistrant.swift .', # https://github.com/nicklockwood/SwiftFormat, not https://github.com/apple/swift-format 
  'ktlint --format "android/**/*.kt"', # https://github.com/pinterest/ktlint.
]

[tasks.codegen]
description = "Generate code"
run = [
  'dart run pigeon --input pigeons/push_api.dart',
]
# TO support macOS, we run codegen for all platforms (except iOS and macOS) twice so that we can run on iOS and macOS, but it's idempotent so it's okay. 
# Ideally, Pigeon supports multiple paths for the same language (a swiftOut [array])
# 'dart run pigeon --input pigeons/push_api.dart --swift_out ./push/macos/Classes/serialization/PushApi.swift',

[tasks.publish]
description = "Publish to pub.dev"
run = [
  # Try `flutter pub publish --dry-run` first
  'flutter pub publish',
]
