name: push
description: Push notifications in Flutter without firebase_messaging for Android, iOS and macOS.
version: 3.3.0
repository: https://github.com/ben-xD/push
issue_tracker: https://github.com/ben-xD/push/issues
homepage: https://tlduck.com/

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' and Android 'package' identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    implements: push
    platforms:
      # Shared implementation for darwin (iOS and macOS) as per https://docs.flutter.dev/packages-and-plugins/developing-packages#shared-ios-and-macos-implementations
      ios:
        pluginClass: PushPlugin
        sharedDarwinSource: true
      macos:
        pluginClass: PushPlugin
        sharedDarwinSource: true
      android:
        package: uk.orth.push
        pluginClass: PushPlugin
  uses-material-design: false

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  pigeon: ^22.7.2

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
