#!/usr/bin/env bash

############################
### CONFIGURATION STARTS ###
############################
TEAM_ID="" # your team id located in the developer portal
KEY_ID="" # your key id located in the developer portal
SECRET="/Users/user/.apple/AuthKey_XXXXXXXX.p8" # the path to the key file you have stored in a safe place
BUNDLE_ID="com.example.bundle_id" # your app bundle ID
APNS_DEVICE_TOKEN="" # your device push token
##########################
### CONFIGURATION ENDS ###
##########################

is_background_message='false'

print_usage() {
  printf "Script to send push notification to iOS devices by their device token.\n"
  printf "  Options:\n"
  printf "    -b : Send background message - a notification without showing an alert to the user. Defaults to False.\n"
}

while getopts 'bv' flag; do
  case "${flag}" in
    b) is_background_message='true' ;;
    *) print_usage
       exit 1 ;;
  esac
done

# Get directory of file
CURRENT_DIR=$(dirname $0)

# make input base64 url safe
function base64URLSafe {
openssl base64 -e -A | tr -- '+/' '-_' | tr -d =
}

# sign input with you key file
function sign {
printf "$1"| openssl dgst -binary -sha256 -sign "$SECRET" | base64URLSafe
}

# now
time=$(date +%s)

# your header section
#
# e.g.
# {
# "alg" : "ES256",
# "kid" : "ABC123DEFG"
# }
header=$(printf '{ "alg": "ES256", "kid": "%s" }' "$KEY_ID" | base64URLSafe)

# your claims section
#
# e.g.
# {
# "iss": "DEF123GHIJ",
# "iat": 1437179036
# }
claims=$(printf '{ "iss": "%s", "iat": %d }' "$TEAM_ID" "$time" | base64URLSafe)

# concatenate your header, your claim and a signed version of you header concatenated with your claim

jwt="$header.$claims.$(sign $header.$claims)"

ENDPOINT=https://api.sandbox.push.apple.com:443

URLPATH=/3/device/

URL=$ENDPOINT$URLPATH$APNS_DEVICE_TOKEN

if [ $is_background_message == "true" ]; then
echo "Sending a background notification..."
curl -v \
 --http2 \
 --header "apns-push-type: background" \
 --header "authorization: bearer $jwt" \
 --header "apns-topic: ${BUNDLE_ID}" \
--data @"$CURRENT_DIR/background_message.json" \
 "${URL}"
else
echo "Sending an alert notification..."
curl -v \
--http2 \
--header "apns-push-type: alert" \
--header "apns-priority: 10" \
--header "authorization: bearer $jwt" \
--header "apns-topic: ${BUNDLE_ID}" \
--header "Content-Type: application/json" \
--data @"$CURRENT_DIR/alert_message.json" \
"${URL}"
fi