name: push_platform_interface
description: Push notifications in Flutter without firebase_messaging.

# NOTE: We strongly prefer non-breaking changes, even at the expense of a
# less-clean API. See https://flutter.dev/go/platform-interface-breaking-changes
version: 0.7.0
repository: https://github.com/ben-xD/push
issue_tracker: https://github.com/ben-xD/push/issues?q=is%3Aissue+is%3Aopen
homepage: https://orth.uk/

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  pigeon: ^22.7.2
  flutter_lints: ^3.0.2
